CAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := mosquitto.conf
LOCAL_VENDOR_MODULE := true
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR_ETC)
LOCAL_SRC_FILES := mosquitto.conf
include $(BUILD_PREBUILT)


